settings:
  ranges:
    hug: 3.0
    hug-message: 50.0
    greet-message: 50.0

  timeouts:
    respect: 60
    cooldown-hug: 10
    cooldown-greet: 5

messages:
  greetings:
    - "<#7ed957>{player1} <#e0e0e0>–ø—Ä–∏–≤–µ—Ç—Å—Ç–≤—É–µ—Ç <#7ec8e3>{player2}"
    - "<#7ec8e3>{player1} <#e0e0e0>–º–∞—à–µ—Ç <#7ed957>{player2}"
    - "<#e0e0e0>{player1} <#7ed957>—É–ª—ã–±–∞–µ—Ç—Å—è <#7ec8e3>{player2}"
    - "<#7ed957>{player1} <#e0e0e0>–∂–µ–ª–∞–µ—Ç —Ö–æ—Ä–æ—à–µ–≥–æ –¥–Ω—è <#7ec8e3>{player2}"

  hugs:
    - "<#f7b2ad>ü§ó <#7ed957>{player1} <#e0e0e0>–æ–±–Ω–∏–º–∞–µ—Ç <#7ec8e3>{player2} <#f7b2ad>ü§ó"
    - "<#7ec8e3>‚äÇ((„Éª‚ñΩ„Éª))‚äÉ <#e0e0e0>{player1} <#7ed957>‚Üí <#e0e0e0>{player2}"
    - "<#e0e0e0>{player1} <#7ed957>–¥–∞—Ä–∏—Ç —Ç–µ–ø–ª—ã–µ –æ–±—ä—è—Ç–∏—è <#7ec8e3>{player2}"
    - "<#7ed957>{player1} <#e0e0e0>–∫—Ä–µ–ø–∫–æ –æ–±–Ω–∏–º–∞–µ—Ç <#7ec8e3>{player2}"

  respects:
    - "<#bdbdbd>‚ö∞ <#e0e0e0>{player} –ø–æ—á—Ç–∏–ª(–∞) –ø–∞–º—è—Ç—å <#bdbdbd>{dead_player} <#bdbdbd>‚ö∞"
    - "<#e0e0e0>üïØ {player} —Å–∫–æ—Ä–±–∏—Ç –ø–æ <#bdbdbd>{dead_player} <#e0e0e0>üïØ"
    - "<#bdbdbd>{player} <#e0e0e0>–≤—Å–ø–æ–º–∏–Ω–∞–µ—Ç <#bdbdbd>{dead_player}"

  errors:
    no-target: "<#f08080>–ò–≥—Ä–æ–∫ –Ω–µ –Ω–∞–π–¥–µ–Ω! –ü–æ–¥–æ–π–¥–∏—Ç–µ –±–ª–∏–∂–µ (–º–∞–∫—Å. {distance} –±–ª–æ–∫–æ–≤)"
    player-offline: "<#f08080>–ò–≥—Ä–æ–∫ –æ—Ñ—Ñ–ª–∞–π–Ω!"
    cooldown: "<#ffe066>–ü–æ–¥–æ–∂–¥–∏—Ç–µ {time} —Å–µ–∫."
    no-recent-death: "<#bdbdbd>–ù–µ—Ç –Ω–µ–¥–∞–≤–Ω–∏—Ö —Å–º–µ—Ä—Ç–µ–π"
    usage: "<#ffe066>–ò—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ: <#7ed957>/hi <–Ω–∏–∫> <#bdbdbd>–∏–ª–∏ <#7ed957>/q <–Ω–∏–∫>"
    self-action: "<#f08080>–ù–µ–ª—å–∑—è –≤—ã–ø–æ–ª–Ω–∏—Ç—å —ç—Ç–æ –¥–µ–π—Å—Ç–≤–∏–µ –Ω–∞ —Å–µ–±–µ"